### ISSUE TITLE
Error: Unexpected token  in JSON at position 111 | Multiline Secret is failing

### ISSUE THREAD

**Issue by mtahaahmed** [kanga333/variable-mapper#30]
Hi, We are using this mapper for our actions. This is how it looks like:

```
jobs:
  dispatch-deployment:
    name: Connecting to GCP Cluster
    runs-on: ubuntu-latest
    steps:
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ github.event.inputs.deployment_destination }}"
          map: |
            {
              "testing": {
                "environment": "testing",
                "project": "testing",
                "service_account_key": "${{ secrets.GCP_SA_KEY }}",
                "cluster_name": "testing-cluster-v3",
                "location": "europe-west1-b",
                "cluster_short_name": "tst-v3"
              }
            }
```

Now the error we are getting is:

```
    export_to: log,env
    mode: first_match
Error: Unexpected token 
 in JSON at position 111
```

And on further investigation, we found that position 111 is the `"${{ secrets.GCP_SA_KEY }}"` part.

So initially we tested it with a single line secret (like in the docs i.e. AWS secret or ID) and it was working fine but here in our scenario is a GCP service account key which is multiline.

**Comment by kanga333** [comment]
@mtahaahmed Thanks for your report.

This is due to the fact that the map parameter that expands `${{ secrets.GCP_SA_KEY }}` is an invalid JSON. You need to escape the letter `${{ secrets.GCP_SA_KEY }}` to make it a valid JSON.

Try the following code.

```yaml
jobs:
  dispatch-deployment:
    name: Connecting to GCP Cluster
    runs-on: ubuntu-latest
    steps:
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{ github.event.inputs.deployment_destination }}"
          map: |
            {
              "testing": {
                "environment": "testing",
                "project": "testing",
                "service_account_key": ${{ toJSON(secrets.GCP_SA_KEY) }},
                "cluster_name": "testing-cluster-v3",
                "location": "europe-west1-b",
                "cluster_short_name": "tst-v3"
              }
            }
```

`toJSON` is a function to escape a string into a JSON string.

I have confirmed that multi-line input is possible with the following sample code.

https://github.com/kanga333/github-actions-playgruond/blob/main/.github/workflows/success_case.yml

Result is
https://github.com/kanga333/github-actions-playgruond/runs/2481425582?check_suite_focus=true
