### ISSUE TITLE
Reference an external file containing the json map

### ISSUE THREAD

**Issue by nwaughachukwuma** [kanga333/variable-mapper#59]
It would be nice if we can make reference to an external file containing the map.

**Comment by mrmeyers99** [comment]
It would be nice if this was supported out of the box.  The simplest way I found to do it is like this:

```
      - id: var-map
        run: |
          echo ::set-output name=content::$(cat ./.github/env_vars.json)

      - uses: kanga333/variable-mapper@master
        id: export
        with:
          key: "key"
          map: ${{ steps.var-map.outputs.content }}
          export_to: log,output
```

**Comment by nwaughachukwuma** [comment]
OK thanks @kanga333. And thanks @mrmeyers99

**Comment by RafPe** [comment]
@mrmeyers99 I use with just passing the value as env but you can as well pass the map from output of your step 

```
      - uses: kanga333/variable-mapper@master
        id: export
        with:
          key: "${{ env.CI_ACTION_REF_NAME }}"
          export_to: env,log,output
          map: '${{ vars.CICD_CONFIG_STRATEGY_MAPPER }}'
```
